server:
  port: 8000

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        heart-beat-timeout: 15000
        heart-beat-interval: 5000
        namespace: dev
        username: nacos
        password: nacos
    gateway:
      discovery:
        locator:
          #允许网关通过服务发现组件，找到其他微服务
          enabled: true
      routes:
        - id: router-user
          uri: lb://user-service
          predicates:
            - Path=/user-service/user/**
        - id: router-content
          uri: lb://content-service
          predicates:
            - Path=/content-service/**
      globalcors:
        cors-configurations:
          '[/**]':
            #允许请求来源
            allowedOriginPatterns: '*'
            #允许携带的头信息
            allowedHeaders: '*'
            #允许的请求方式
            allowedMethods: '*'
            #是否允许携带cookies
            allowCredentials: 'true'
            #跨域检测的有效期，会发起一个OPTION请求
            maxAge: '3600'

